services:
  song_recommendation_system:
    image: kCHORDS/recommendation_system_notebook
    container_name: kCHORDS-recommendation_system_notebook
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
        - 9999:9999
    env_file:
      - .env
    volumes:
      - .:/app
    command: jupyter notebook --NotebookApp.token='' --allow-root --ip=0.0.0.0 --port=9999